#!/bin/bash

# noclobber: prevent accidental file overwrite
# nounset: error on undefined variables
set -o noclobber -o nounset

# Script arguments passed by lf
FILE_PATH="${1}"         # Full path of the highlighted file
HEIGHT="${2}"            # Height of preview pane in terminal lines

handle_mime() {
    local mimetype="${1}"
    case "${mimetype}" in
	text/html) w3m -dump "${FILE_PATH}" ;;
	text/troff) man ./ "${FILE_PATH}" | col -b ;;
	text/* | */xml)
            if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
                exit 2
            fi
            if [ "$( tput colors )" -ge 256 ]; then
                local highlight_format='xterm256'
            else
                local highlight_format='ansi'
            fi
            highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
                --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}" ;;
	application/zip) atool --list -- "${FILE_PATH}" ;;
        image/*) chafa --fill=block --fit-width --symbols=block --colors 256 "${FILE_PATH}" || exit 1;;
        video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" || exit 1;;
        */pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - | head -n 30 ;;
        *opendocument*) odt2txt "${FILE_PATH}" ;;
    esac
}

MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
handle_mime "${MIMETYPE}"
exit 1
