#!/bin/bash

# noclobber: prevent accidental file overwrite
# nounset: error on undefined variables
set -o noclobber -o nounset

# Script arguments passed by lf
FILE_PATH="${1}"         # Full path of the highlighted file
HEIGHT="${2}"            # Height of preview pane in terminal lines

# Highlight settings
HIGHLIGHT_SIZE_MAX=${HIGHLIGHT_SIZE_MAX:-262143}  # 256KiB
HIGHLIGHT_TABWIDTH=${HIGHLIGHT_TABWIDTH:-4}
HIGHLIGHT_STYLE=${HIGHLIGHT_STYLE:-github-dark}

handle_mime() {
    local mimetype="${1}"
    case "${mimetype}" in
	text/html) w3m -dump "${FILE_PATH}" ;;
	text/troff) man ./ "${FILE_PATH}" | col -b ;;
	application/zip) atool --list -- "${FILE_PATH}" ;;
        image/*) chafa --fill=block --symbols=block --colors 256 "${FILE_PATH}" || exit 1;;
        video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" || exit 1;;
        */pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - | head -n 30 ;;
        *opendocument*) odt2txt "${FILE_PATH}" ;;
        *)
            file_size=$(stat -f%z -- "${FILE_PATH}" 2>/dev/null || echo 0)
            if [ "${file_size}" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
                exit 2
            fi
            if [ "$( tput colors )" -ge 256 ]; then
                local highlight_format='xterm256'
            else
                local highlight_format='ansi'
            fi
            if [ -f "$HOME/.config/highlight/themes/${HIGHLIGHT_STYLE}.theme" ]; then
                highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
                    --wrap --config-file="$HOME/.config/highlight/themes/${HIGHLIGHT_STYLE}.theme" --force -- "${FILE_PATH}"
            else
                highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
                    --wrap --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}"
            fi
            ;;
    esac
}

MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
handle_mime "${MIMETYPE}"
exit 1
